### ISSUE TITLE
`:Telescope symbols` throws `attempt to call field 'create' (a nil value)`

### ISSUE THREAD

**Issue by joshfrench** [nvim-telescope/telescope-symbols.nvim#5]
**Expected behavior:**
A telescope picker

**Actual behavior:**
`E5108: Error executing lua .../nvim/plugged/telescope.nvim/lua/telescope/pickers.lua:302: attempt to call field 'create' (a nil value)`

**To reproduce:** 
- Put any valid json symbol source in the rtp, e.g. `~/.config/nvim/data/telescope-sources/emoji.json`
- Start nvim
- `:Telescope symbols`

**Environment:**
- Latest version of `telescope.nvim` installed via `:PlugUpdate telescope.nvim`
- Neovim v0.5.0 installed via homebrew
- Telescope config:
```
local actions = require("telescope.actions")
local action_state = require("telescope.actions.state")
local custom_actions = {}
function custom_actions.fzf_multi_select(prompt_bufnr)
    local picker = action_state.get_current_picker(prompt_bufnr)
    local num_selections = table.getn(picker:get_multi_selection())

    if num_selections > 1 then
        actions.send_selected_to_qflist(prompt_bufnr)
        actions.open_qflist()
    else
        actions.file_edit(prompt_bufnr)
    end
end
require'telescope'.setup{
  defaults = {
    path_display = {"shorten"},
    mappings = {
            i = {
                -- close on escape
                ["<esc>"] = actions.close,
                ["<tab>"] = actions.toggle_selection + actions.move_selection_previous,
                ["<s-tab>"] = actions.toggle_selection + actions.move_selection_next,
                ["<cr>"] = custom_actions.fzf_multi_select
            },
            n = {
                ["<tab>"] = actions.toggle_selection + actions.move_selection_previous,
                ["<s-tab>"] = actions.toggle_selection + actions.move_selection_next,
                ["<cr>"] = custom_actions.fzf_multi_select
            }
        }
  }
}
```

**Comment by fdschmidt93** [comment]
If you get this error, this should not be specific to `telescope-symbols` but apply to any picker. 

See https://github.com/nvim-telescope/telescope.nvim/issues/1105

In brief, please check that `telescope.nvim` and `plenary.nvim` are both up to date and that no stale version, in particular of `plenary`, are in your `runtimepath`.

`lua print(vim.inspect(require"plenary.popup"))` should look like this. If not, it's one of the aforementioned issues.

```lua
{                                                                                                                                                                                      
  _callbacks = {},
  _hidden = {},
  _pos_map = {
    botleft = "SW",
    botright = "SE",
    topleft = "NW",
    topright = "NE"
  },
  create = <function 1>,
  execute_callback = <function 2>
}

```

**Comment by joshfrench** [comment]
@fdschmidt93 Thanks, that did the trick!
