### ISSUE TITLE
How to lazy load this extension with `packer.nvim`

### ISSUE THREAD

**Issue by younger-1** [nvim-telescope/telescope-symbols.nvim#6]
I tried the following, but it didn't work as expected

```lua
  {
    "nvim-telescope/telescope-symbols.nvim",
    -- event = "BufRead",
    cmd = "Telescope",
  },
```
If I use `event` trigger, it works.
But I an looking forward to use `cmd` or `keys` trigger like above.

**Comment by Conni2461** [comment]
Actually you dont. This repo doesnt even have lua/vim files that will be loaded. Its a repo to store json data and a lua/julia script to pull the latest data in a json file. The json files will be loaded on running `:Telescope symbols`.

You can also just download the json files (sources) you want and put them in any path that you wanna have. After that you just have to call `Telescope symbols` with that path. See `:help builtin.symbols()`

**Comment by younger-1** [comment]
Thanks for your reply~
