### ISSUE TITLE
Nerd Fonts

### ISSUE THREAD

**Issue by bennypowers** [nvim-telescope/telescope-symbols.nvim#9]
:wave:

Hello! Love the plugin. Please consider adding a built-in source for NerdFont symbols

Thanks :)

**Comment by bennypowers** [comment]
It could be based on this file, or a modified version of it

https://github.com/sudormrfbin/cheatsheet.nvim/blob/master/cheatsheets/cheatsheet-nerd-fonts.txt

**Comment by folliehiyuki** [comment]
You can check out my PR: https://github.com/nvim-telescope/telescope-symbols.nvim/pull/7

**Comment by Conni2461** [comment]
merged
